### PR TITLE
tests failing, seems unrelated

### PR DESCRIPTION
**Pull request by wschwab**
### What was wrong?

#1195 : Making one consistent syntax for Enums across the codebase.

### How was it fixed?

Using `git grep` to find instances of Enums, then updating so that all followed SNAKE_CAPS.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history
- [x] Currently breaking tests, see #1218 , needs fixing

### CODE REVIEW

**Comment by pipermerriam** [comment]
If you run the lint tests I think you'll see there's at least one that wasn't updated under `StoreBlockBodies`

**Comment by wschwab** [comment]
@pipermerriam I totally missed that - fixing up `StoreBlockBodies` took care of the lint tests and a couple of others, but now I'm getting a couple of fails that look sort of random to me (`py36-integration` and `py37-wheel-cli`). I tried going through the traces there, but couldn't extract something relevant to the codebase.

What do you suggest?

**Comment by ralexstokes** [comment]
@wschwab thanks for your help! the two failures i can see in CI right now are known bugs we have in our tests and should be unrelated to your work. so you can ignore them :)

**Comment by wschwab** [comment]
Great! So I'm all done from my side?

**Comment by cburgdorf** [comment]
Unrelated to this PR but I just merged https://github.com/ethereum/trinity/pull/1216 which should reduce the (unrelated) failure that you've hit there

**Pull request merged**
