### PR TITLE
Add snapcraft.yaml, for building snap packages

### PR DESCRIPTION
**Pull request by lithp**
At part of https://github.com/ethereum/trinity/issues/1158 I'm experimenting with making installing Trinity a `snap install trinity` away.

To build this:

```bash
$ sudo snap install snapcraft --classic  # installs snapcraft, the snap build tool
$ snapcraft  # (from inside the trinity root dir), this builds the snap
$ sudo snap install --devmode --dangerous trinity-client_0.1.0-alpha.29_amd64.snap
# now you're ready to run trinity!
$ trinity-client.trinity  # This name is ugly, I'm hoping we can get approval for the command to be "trinity"
```

To try out the snap for yourself (I've built the package and uploaded it):

```bash
$ sudo snap install --edge --devmode trinity-client
```

### To-Do

- [ ] After installing the snap it's slower than usual to start, look into why it's slower and whether that's resolvable. 
- [ ] I've asked for the "trinity" name, I should eventually followup if they don't respond.
- [ ] Lahja is failing to connect to itself, so the processes can't talk to each other. Figure out why!
- [ ] Also expose the `trinity-beacon` command and make sure it works.
- [ ] To publish this snap we need to switch to strict confinement, which means somehow giving the snap access to `/dev/shm/sem.*` and `/proc/*/mounts`, those two things are currently failing because of confinement. (Related: https://lists.ubuntu.com/archives/snapcraft/2017-February/003093.html)
- [ ] Add some kind of github action which automatically publishes a snap when master is updated or when a release is made.
- [ ] Add some kind of test that the package builds correctly?

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

[//]: # (See: https://trinity-client.readthedocs.io/en/latest/contributing.html#pull-requests)
- [ ] Add entry to the [release notes](https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by mhchia** [comment]
`snap` looks pretty cool! Some questions:
- Do we need to install `snap` first before running `trinity-client.trinity`?
- Is `snap` cross-platform(at least for Linux, OS X and Windows)?

**Comment by lithp** [comment]
Hey @mhchia, sorry for taking a while to respond, I didn't notice this!

> Do we need to install snap first before running trinity-client.trinity?

If you're running Ubuntu, then snap is already installed! Otherwise, yes, you'll need to install snap first. Though, it looks like doing so it pretty simple for most distributions: https://snapcraft.io/docs/installing-snapd

> Is snap cross-platform(at least for Linux, OS X, and Windows)?

snap is linux-only, I haven't started looking into osx and I have a long and infinite list of things I want to get to before I try to get Trinity working on Windows :laughing:

**Comment by ralexstokes** [comment]
just to chime in here @lithp @mhchia i have it on my list to look at `brew install trinity` on `macOS`, but if one of you gets there first just lmk

**Comment by pipermerriam** [comment]
cc @njgheorghita who I believe has done a `brew install` for the `ethpm-cli`

**Comment by lithp** [comment]
Closing this for now in lieu of the AppImage support which can reach more people: https://github.com/ethereum/trinity/pull/1205

**Comment by lithp** [comment]
Well, if this work is ever picked up again I just got an email, we're approved to use the "trinity" package name!

**Pull request closed without merging**
