### PR TITLE
Release notes for v0.1.0-alpha.25

### PR DESCRIPTION
**Pull request by cburgdorf**
This is the long-running PR for release notes to be included in the next release.

Community contributors are welcome to comment below with your notes, or open a PR to merge into this branch.

Coders with write access are welcome to add commits on top. Please don't force push, though: it would be sad to accidentally blow away someone else's notes.

### CODE REVIEW

**Comment by carver** [comment]
Thanks! I guess we could add this step to the end of the release docs, I forgot :)

**Comment by carver** [comment]
After we merge in #699 I'll have to rebase this, so please hold off on pushing any release note commits for a day or two.

If you add a comment on this thread, I'll add it to the PR after rebasing.

**Comment by carver** [comment]
> so please hold off on pushing any release note commits for a day or two.

Rebase complete. Feel free to add your own release note commits again.

**Comment by cburgdorf** [comment]
We use towncrier now for our release notes. Find out more: https://github.com/ethereum/trinity/blob/master/newsfragments/README.md

**Pull request closed without merging**
