### PR TITLE
Use asyncio-run-in-process to run the DBManager

### PR DESCRIPTION
**Pull request by gsalgado**
Closes: #1188

### CODE REVIEW

**Comment by pipermerriam** [comment]
What is keeping us from going ahead and getting this running in its own process (as its own process leader)?

**Comment by gsalgado** [comment]
> What is keeping us from going ahead and getting this running in its own process (as its own process leader)?

I recently tried to do that for `TrioIsolatedComponent` (which uses `multiprocessing` like the `DBManager`), and realized it'd take a lot of work because we can't use `asyncio-run-in-process` there, but I guess we could turn `trinity.main.run_database_process()` into an async function so that we can use `asyncio-run-in-process` to run the `DBManager`, and that way we can make it run on a separate process group?

**Comment by pipermerriam** [comment]
Are you aware of https://github.com/ethereum/trio-run-in-process

It's less mature than `asyncio-run-in-process` but should be in a state that is viable to start off with.

**Comment by gsalgado** [comment]
I had seen that but was under the impression it was still in an embryonic state, don't know why. Have you tried using it on `TrinityIsolatedComponent`?

Anyway, do you think it makes sense to wrap the `DBManager` runner into an async API just so that we can use `asyncio-run-in-process`?

**Comment by gsalgado** [comment]
It seemed to me like introducing the concept of dependency between components to the ComponentManager would be a significant undertaking, with the possibility of opening up a few more cans of worms, so I decided to just try to use asyncio-run-in-process (and refactor a few things) to run the `DBManager` process. I've managed to get it working, but now we're getting an asyncio warning because asyncio-run-in-process seems to be ignoring the exception of a task, even though it attempts to wait for it twice (as we can see in the RuntimError that is the task's exception that is being ignored);

```
    INFO  2020-04-29 14:48:31,605             DBManager  Got KeyboardInterrupt, returning
Task exception was never retrieved
future: <Task finished coro=<run_db_manager() done, defined at /home/salgado/src/trinity/trinity/bootstrap.py:351> exception=RuntimeError('cannot reuse already awaited coroutine')>
RuntimeError: cannot reuse already awaited coroutine
```

This should not really come as a surprise as we still haven't figured out what's going on in https://github.com/ethereum/asyncio-run-in-process/pull/12, and `asyncio-run-in-process` has some code that awaits for a coroutine multiple times (https://github.com/ethereum/asyncio-run-in-process/blob/87e3cf4303790bcf7a965c372999f81ec585598f/asyncio_run_in_process/_child.py#L94-L101), which asyncio doesn't seem to like

I'll get back to it tomorrow, but thought I'd post this update just in case

**Comment by pipermerriam** [comment]
> It seemed to me like introducing the concept of dependency between components to the ComponentManager would be a significant undertaking, with the possibility of opening up a few more cans of worms

Fair, but I'm still somewhat convinced that this is the direction we need to move towards.  Otherwise, we need a different mechanism to solve the fundamental base problem which is:

- we have components that depend on each other.
- if `A` depends on functionality of `B` then:
    - `A` should not be started until `B` starts
    - `B` should not be stopped until `A` is stopped

In my head the structure is simple and the complexity is not that different from the current complexity since a component that doesn't shutdown cleanly today will also not shutdown cleanly in this new dependency based model as the shutdown mechanism shouldn't be that different, only the order in which the shutdowns are issued.

The optimist in me thinks that it may actually result in things being cleaner since it institutes more control and order to the lifecycles and may eliminate weird bugs like when the `DBManager` shuts down before the other components which are still using it.  In the new model this type of error shouldn't occur.

**Comment by pipermerriam** [comment]
I'll point out that we could in theory solve this problem at a more granular level and figure out how to have the `DBManager` wait for all of it's connections to close before shutting down, but I feel like this approach is more likely to result in more unclean shutdowns since it means that some components would have to *block* shutdown while waiting for things like this and it's not unreasonable to expect us to accidentally bake in some sort of accidental circular dependency where `A` waits on `B` which waits on `C` which waits on `A`, all via implicit mechanisms within the component that aren't obviously visible.

No need to prove me wrong or argue against the complexity.  I'm very ok with you taking whatever path forward you feel is best and most actionable.

**Comment by gsalgado** [comment]
This is working fine now, and I've also refactored a few things to get rid of some code duplication. BTW, since we're now using `asyncio_run_in_process` to run the DBManager *and* the only place that deals with the DB manager/process is the new `_run()` method (https://github.com/ethereum/trinity/pull/1701/files#diff-5c2d4b3cd13a63d555a9b179b7bc741dR244), it would actually be easier to turn it into an isolated component and use the `ComponentManager` to run it, if we want to go that way

**Pull request merged**
