### PR TITLE
Fix broken docker image build

### PR DESCRIPTION
**Pull request by gsmadi**
### What was wrong?

During docker image build, snappy was not being installed which is a requirement now.

### How was it fixed?

Install `libsnappy-dev` during docker image build.

[//]: # (For important changes, please add a new entry to the release notes file)
[//]: # (See: https://trinity-client.readthedocs.io/en/latest/contributing.html#pull-requests)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by pipermerriam** [comment]
Is there a way for us to test the Docker image within our CI setup?

**Comment by gsmadi** [comment]
Yes most definitely feasible to build a test image with CircleCI. Will include a job in this PR.

Maybe, we could do:
- Build test image to ensure docker builds work
- Start a container with the built test image and run `trinity --help` to ensure all was installed correctly

**Comment by cburgdorf** [comment]
@gsmadi that sounds like a good approach :+1:

**Comment by gsmadi** [comment]
The above suggestion is implemented and build passing should be a good indicator of good docker builds so we can start distributing more frequently.

**Pull request merged**
