### PR TITLE
Issue #1959 easier upnp support

### PR DESCRIPTION
**Pull request by Elnaril**
## What was wrong?
Only a limited number of upnp services are listed to setup portforwarding.
The list is hardcoded, it is not straight forward for users to identify the one used by their routers, and it is currently not possible to provide a specific one to Trinity.
See Trinity Issue https://github.com/ethereum/trinity/issues/1959 for more details

## How was it fixed?
The proposed enhancement is divided in 2 parts:

 1/ In ethereum/upnp-port-forward/client.py:
 - A new method `fetch_add_portmapping_services` retrieves and returns all available services which can map ports.
 - The method `setup_port_map` can now receive a service name as a new argument and uses it first to when it tries to map a port.
This part has been submitted with the PR https://github.com/ethereum/upnp-port-forward/pull/5

 2/ In ethereum/trinity:
 - A new component `UpnpServiceNamesComponent` exposes the new command line positional argument `export-upnp-info`, calls `fetch_add_portmapping_services` and print the results, if any, on the terminal.
 - The component `UpnpComponent` exposes now a new command line optional argument `--upnp-service-name` which allows the user to provide a upnp service name to Trinity. This service name is provided to the function `setup_port_map`.

### To-Do

**This PR depends on https://github.com/ethereum/upnp-port-forward/pull/5 to pass the CI tests.**

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/upnp-port-forward/blob/master/newsfragments/README.md)

[//]: # (See: https://upnp-port-forward.readthedocs.io/en/latest/contributing.html#pull-requests)
- [ ] Add entry to the [release notes](https://github.com/ethereum/upnp-port-forward/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by pipermerriam** [comment]
@Elnaril thank you for doing this work.  I'm having a small change of heart and thinking that I'd rather drop this into the actual upnp library itself.  You could put it in `upnp_port_forward/tools/export.py` and make it so that you can do either `python upnp_port_forward/tools/export.py` or `python -m upnp_port_forward.tools.export` and have it dump to stderr.

**Comment by Elnaril** [comment]
@pipermerriam thanks for the review.
I understand that the _export_ part can be done by the `upnp-port-forward` library, but what about the `--upnp-service-name` part ?
If we don't want to be able to provide a specific service name to Trinity, do we still need to implement the corresponding feature in `upnp-port-forward` ?

**Comment by pipermerriam** [comment]
Ah yes, we would still want the ability to specify the device.

**Comment by Elnaril** [comment]
@pipermerriam , indeed moving the export part in `upnp-port-forward` makes great sense to me, but would it really help the users of Trinity if it's only accessible from there ?
If someone is interested in using Trinity, it may not be straightforward to think of using one of its libraries to discover the available upnp services, especially if using Docker. But it may be more common for a Trinity user to consult Trinity help and find out there is an option to do it from Trinity, even if Trinity is just a pass-through.
I understand though that this option would be a bit remote to Trinity's actual purpose ... it's just a thought to help the spreading of Trinity ...

**Comment by pipermerriam** [comment]
:+1: I'm ok mirroring the export functionality here.

**Pull request closed without merging**
