### PR TITLE
Regenerate 1000pow_headers fixture under latest VM rules

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

The current `1000pow_headers` fixture was created under the VM rules of Byzantium (the latest rules at the time of creation). I want to build an uncle chain to this fixture but instead of sticking to byzantium I think it is better to simply update the old fixture.

### How was it fixed?

Updated `1000pow_headers` fixture to use the latest chain rules.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

[//]: # (See: https://trinity-client.readthedocs.io/en/latest/contributing.html#pull-requests)
- [ ] Add entry to the [release notes](https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by carver** [comment]
Hm, I'm not keen to drop/add ~1MB from the repo every time there's a network change. It will make checking out trinity painfully slow after a while. Just configuring the test to use `Byzantium` sounds better than that to me.

I'm up for considering other options, though.

**Comment by cburgdorf** [comment]
>Hm, I'm not keen to drop/add ~1MB from the repo every time there's a network change

Mmh..ok, I didn't consider that. 

I had actually started by adding an additional parameter to this API to be able to over rule the `latest_mainnet_at(0)`.

https://github.com/ethereum/trinity/blob/fc57875d779d9528df03f629e352c60cc6ecd61b/tests/core/integration_test_helpers.py#L34-L53

But I thought it would be cleaner to just update the fixtures to the latest VM rules instead.

>I'm up for considering other options, though.

Anything else that would come to your mind? Like hosting the zips elsewhere and curling them in?

**Comment by cburgdorf** [comment]
Another idea could be to use a submodule to load in fixtures (similar to `ethereum/tests`). I think that **not** upgrading the fixtures to newer VM rules might get messy over time. E.g. we might need fixtures with newer opcodes to test specific things etc.

**Comment by carver** [comment]
> I had actually started by adding an additional parameter to this API to be able to over rule the `latest_mainnet_at(0)`.

I think this is an okay/good medium term solution.

> I think that **not** upgrading the fixtures to newer VM rules might get messy over time. E.g. we might need fixtures with newer opcodes to test specific things etc.

I don't really expect it to be a *super* common need to test things where POW must be valid, and we need a bunch of headers in a row. But if the cases start piling up, we can think about other options.



> > I'm up for considering other options, though.
> 
> Anything else that would come to your mind? Like hosting the zips elsewhere and curling them in?

I guess? It sounds pretty rough to me. Maybe a submodule? Or AIUI there's a way to trim old objects out of the git history, but obviously we would want to be _very_ careful about doing something like that. That's why I'm still in favor of just passing in the VM to use, for now.

**Comment by cburgdorf** [comment]
Regenerated the uncle fixture on byzantium. Closing

**Pull request closed without merging**
