### PR TITLE
Upgrade lahja to 0.10.1

### LINKED ISSUE #98: Exception from lahja escaping py-evm shutdown.
### What is wrong?

This is escaping during a py-evm shutdown.

```
   ERROR  12-15 15:31:54               asyncio  _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=InvalidStateError('invalid state',)>
Traceback (most recent call last):
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/lahja/endpoint.py", line 123, in _connect_receiving_queue
    self._process_item(item, config)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/lahja/endpoint.py", line 148, in _process_item
    future.set_result(item)
asyncio.base_futures.InvalidStateError: invalid state
```

### How can it be fixed

Have not investigated.

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

Upgrade lahja to `0.10.1` to potentially improve stability and fix #98 

### How was it fixed?

Change `setup.py` 

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by veox** [comment]
Confirming that this fixes `InvalidStateError` escaping. However, I still get a (possibly unrelated!):

``` python
   ERROR  01-08 19:11:59               asyncio  _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
concurrent.futures._base.CancelledError
```

This does not happen if I `<CTRL>+C` immediately after start-up, e.g. at this moment:

``` python
    INFO  01-08 19:10:49             IPCServer  IPC started at: /home/veox/.local/share/trinity/mainnet/ipcs-eth1/jsonrpc.ipc
^C    INFO  01-08 19:10:50               trinity  Shutting down Trinity (CTRL+C / Keyboard Interrupt)
```

... but it does after a little bit - by time `FastChainBodySyncer` has printed a couple log messages.

**Comment by cburgdorf** [comment]
>Confirming that this fixes `InvalidStateError` escaping

Nice! So, does that mean you were able to reproduce this error reliably locally? Because I never experience it myself (other than in artificial lahja debug preparation)

**Comment by veox** [comment]
> Nice! So, does that mean you were able to reproduce this error reliably locally?

Actually, it seems that I can't reproduce it reliably (with `lahja` 0.10.0).

There were two occasions in a row (after running 15-30 minutes) that I could, so I assumed it's reliable. I've tried ~10 more times now (each running 1-3 minutes), and it doesn't happen.

**Comment by cburgdorf** [comment]
@veox Thanks for taking the time to report back!

**Pull request merged**
