### PR TITLE
Send fewer non-urgent GetNodeData queries to peers

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

#2008 

### How was it fixed?

In general, it's not common for a query to already be active, but just in case, we'd rather not queue up more requests for preview or backfill data. (Urgent data, on the other hand, should always be retrieved as quickly as possible, so we allow urgent requests to stack up)

I'm not really sure that this will fix 2008, but it won't hurt, and it might help.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

[//]: # (See: https://trinity-client.readthedocs.io/en/latest/contributing.html#pull-requests)
- [x] ~Add entry to the [release notes](https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)~

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by cburgdorf** [comment]
:+1:  I'm trying latest master + this PR on my DappNode overnight.

**Comment by carver** [comment]
@cburgdorf I fixed the typo. Looks good to run now.

**Comment by cburgdorf** [comment]
The good news is that I haven't gotten any `ConnectionBusy` error with this patch. The bad news is that my node eventually starved and I found it idling without peers this morning. But looking through the logs I can't make a connection between these issues. I will create a separate issue for that to examine.

**Comment by cburgdorf** [comment]
Created https://github.com/ethereum/trinity/issues/2045 for the failed run.

**Review by cburgdorf — APPROVED** [review]
I can confirm that this fixes the `ConnectionBusy` issue :+1:

**Pull request merged**
