### PR TITLE
`trinity` on `trio`

### PR DESCRIPTION
**Pull request by ralexstokes**
NOTE: supersedes #1645.
NOTE: part of a series

I'm working on exposing a `trio`-based Trinity. I'm also taking the opportunity to see if we can't run the beacon node as a single-process (eliminating the fusion of `multiprocessing` and `asyncio` that still seems to be a source of arcane bugs); I'm aiming to write the `trio`-based beacon node in a way that we can easily port to a multiprocess architecture if and when we need that on the eth2 side of things.

I'd suggest reviewing commit by commit. Ideally each commit is a separate PR that is based off the PR made from the previous commit.

This PR introduces the machinery required to run trio-based components on top of the `trinity` platform and demos a basic one in the `beacon_trio.component.BeaconNodeComponent`.

I was originally going to put more commits in this PR to add the beacon node component but this is self-contained at the moment.

#### Cute Animal Picture

put a cute animal picture link inside the parentheses:max_bytes(150000):strip_icc()/cutest-cats-on-the-internet-4-57eead1f5f9b586c354d7ecd.jpeg)

### CODE REVIEW

**Comment by carver** [comment]
I think some things improved lately. You might get a clean pass on the wheel-cli tests if you rebase on master.

**Comment by ralexstokes** [comment]
this was rebased against master just a short while ago -- i'll rerun the wheel-cli tests to see if the pass

**Comment by ralexstokes** [comment]
@carver thanks for the quick review! i'll give @cburgdorf some time to look this over

**Comment by ralexstokes** [comment]
given that CI is passing i'll go ahead and merge this in -- welcome any post-merge feedback (e.g. @cburgdorf )

**Comment by cburgdorf** [comment]
I skimmed over it and it looks all good :+1:

**Pull request merged**
